# curl -s https://citizen.devops.atypon.com/v1/providers/gcp/zabbix/versions    | jq -r .versions[].version  | sort -Vr | head -n1

# curl -s https://citizen.devops.atypon.com/v1/modules/gcp/nodepool/atypon/versions   | jq -r .modules[].versions[].version | sort -Vr | head -n1

steps:
  - name: golang
    entrypoint: 'make'
    args:
      - 'citizen'
  - name: gcr.io/atypon-devops/remote-builder
    entrypoint: 'bash'
    env:
      - JQ=.versions[].version
      - CITIZEN_ADDR=https://citizen.devops.atypon.com
      - INSTANCE_ARGS=--tags=remote-cloud-builder --image-project cos-cloud --image-family cos-stable  --subnet projects/atypon-infra/regions/us-central1/subnetworks/atypon-subnet-infrastructure --no-address
      - USERNAME=cloud-user
      - CITIZEN_IMAGE=us-central1-docker.pkg.dev/atypon-artifact/docker-registry/atypon-devops/citizin:v0.2.2
      - CITIZEN_CONTAINER_ARGS=bash /workspace/pipelineScript.sh
    args:
      - '-c'
      - |
        set -xe
        export COMMAND="docker-credential-gcr configure-docker && docker run -e CITIZEN_ADDR=$${CITIZEN_ADDR} -e JQ=$${JQ} -v /home/cloud-user/workspace:/workspace $${CITIZEN_IMAGE} $${CITIZEN_CONTAINER_ARGS}"
        bash -xe /bin/run-builder.sh
timeout: 3600s